version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    platform: linux/amd64
    container_name: neo4j_danny
    restart: always
    ports:
      - "7478:7474"  # Web 界面
      - "7688:7687"  # Bolt 連接
    environment:
      - NEO4J_AUTH=neo4j/password  # 設定帳號密碼
      - NEO4J_PLUGINS=["apoc"]  # 啟用 APOC 外掛p
    volumes:
      - ./neo4j_data:/data
      - ./backups:/backups
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"  # Redis 服務
      - "8001:8001"  # RedisInsight Web UI
    volumes:
      - ./redis_data:/data
